### ISSUE TITLE
cvxpy switching solver warning

### ISSUE THREAD

**Issue by sgsutcliffe** [andersen-lab/Freyja#125]
I've got a warning from cvxpy when running demix
`cvxpy/problems/problem.py:1337: UserWarning: Solution may be inaccurate. Try another solver, adjusting the solver settings, or solve with verbose=True for more information.
  warnings.warn(
`
The sample was predicted to be:
summarized	[('Other', 0.9989600692533944)]
lineages	XBL XBB.1.29 XBB.1.5.9
abundances	0.98971300 0.00730721 0.00193986
resid	0.8584833412967627
coverage	22.730160853426078
I am guessing cvxpy did not like making that prediction. Should I be flagging this sample?
Happened with cvxpy=1.2.1

**Comment by joshuailevy** [comment]
Hi @sgsutcliffe, 

Sorry for the delay. This is an error that tends to occur with low coverage samples like this. Usually Freyja will still return a result, but since convergence of the solver isn't great cvxpy returns this warning. 

We're planning to incorporate an option relatively soon to group lineages that are indistinguishable given the available seq coverage, since in these cases we often do not have access to enough of the genome to identify a particular lineage. Will follow up on this soon! 

Josh

**Comment by dylanpilz** [comment]
Addressed by #145
