### ISSUE TITLE
Issues with deconvoluting XBB sublineages?

### ISSUE THREAD

**Issue by jake2298** [andersen-lab/Freyja#135]
Hello,

I am coming from this as a public health scientist and not a bioinformatician, so apologies for any incorrect terminologies or assumptions.

We have been using Freyja for >6 months now in our jurisdiction and have seen a very strong positive and significant correlation between our weekly wastewater and clinical SARS-CoV-2 genomic frequencies. 

Recently we started reporting XBB separated into it's sublineages due to the current public health interest. Therefore, we are now reporting XBB.1.5.X, XBB.1.9.X and XBB.1.16.X, which we know based on clinical samples are all currently circulating within our wastewater catchments. During this time, despite having high genome coverage >95% (10x depth) it is apparent that week to week the wastewater genomic abundances are jumping largely (>20% on occasions) between the different XBB sublineages. Additionally, we do not see a strong correlation to clinical data for the XBB sublineages, however, continue to see the strong correlation for the combined XBB sublineages and other circulating parent lineages (CH.1.1.X, XBC.X and BQ.1.X).

Looking at the barcode file,  I could not find a single mutation for XBB.1.5 that was absent in other XBB sublineages. However, there were mutations for the sublineages of XBB.1.5. Therefore, I believe this could be linked to our jurisdiction currently having predominantly XBB.1.5 detected clinically, where more mutations could be used for the XBB.1.5 sublineages.

My question, are there any known issues with Freyja deconvoluting XBB sublineges or other sublineages of high genomic similarity? I note that Biobot (https://biobot.io/data/) do not report XBB.1.5 and assume this may be a commonly known issue. However, I could not find prior information on this.

Kind regards,
Jake

**Comment by joshuailevy** [comment]
Hi Jake, 

Thanks for reaching out! I haven't heard of of other users having similar issues actually, and we're able to resolve differences among these XBB sublineages in our surveillance in San Diego(see [here](https://searchcovid.info/dashboards/wastewater-surveillance/) ). Given the low-ish overall prevalence, we've seen some similar jumping between sublineages (which is not unexpected given that a single cluster can dramatically change the relative lineage abundance when there's few infections in the community. I assume you're working with composite rather than grab samples as well? 


Regarding your point about the lack of additional mutations, I just did a quick check to make sure something hadn't gone awry, looks like the appropriate sublineage mutations are there. I've attached the associated Python script I wrote to check. See for example, 

```
XBB.1.5 mutations beyond XBB: ['G22317T', 'G27915T', 'T17124C', 'T23018C']
XBB.1.9 mutations beyond XBB: ['C12789T', 'G22317T', 'G27915T', 'G5720A', 'T28297C']
XBB.2.3 mutations beyond XBB: ['A22320G', 'C23123T', 'C27431T', 'G29706T', 'T23018C']
```
[check_barcodes.py.txt](https://github.com/andersen-lab/Freyja/files/11451435/check_barcodes.py.txt)

I'm not quite sure why Biobot is only aggregating at the XBB.X level to be honest, given that XBB seems to be sticking around. 

Josh

**Comment by danstrange** [comment]
Hi Josh,

Just to chime in since we are also noticing the XBB discrepancy between clinical and wastewater data.  Our clinical data is tracking XBB* at <1% among statewide variant proportions, whereas our wastewater data (generated by Biobot) is tracking XBB* abundances (tracked separately from XBB.1.16*, XBB.1.5*, XBB.1.9.1*, XBB.1.9.2*) at around 20% statewide.  

-Dan

**Comment by joshuailevy** [comment]
Hey Dan,

Thanks for chiming in! Is it possible that the clinical data is rather delayed or super limited? Fairly surprising to see XBB at such a low proportion given its dominance elsewhere in the country. 

Josh

**Comment by danstrange** [comment]
Hi Josh,

Apologies, just to clarify, XBB* excludes all the other XBBs mentioned (also forgot XBB.1.5.1).   Currently, XBB.1.5* is dominant in both our clinical and wastewater sampling.

As of 4/22/23:

For wastewater, XBB* (excluding the above XBBs) accounts for ~20%, whereas XBB.1.5* accounts for ~65%.
For clinical, XBB* (excluding the above XBBs) accounts for <1%, whereas XBB.1.5* accounts for ~83%.

-Dan

**Comment by jake2298** [comment]
Hi Josh,

Thanks for the reply, I appreciate you looking through the mutations! For our samples where we believe there are issues, we will look to see if there is reduced or no coverage at these positions.

Dan appears to be having a similar issue to us, where we assume some of the XBB.1.5 abundance is being incorporated into the XBB.X abundance (excluding XBB.1.9.X, XBB.1.16.X and XBB.1.5.X). Investigating the XBB.X lineages further in these samples the abundance largely belongs to XBB.1.22.X, a sublineage not detected clinically throughout our state. Where I am from in Australia, we are currently going through an outbreak so have relatively increased SARS-CoV-2 viral concentrations in the wastewater and don't believe it is related to the low level of infections.

Thanks again,
Jake

**Comment by joshuailevy** [comment]
Sorry for the delay all- was traveling at the time and I seem to have missed your responses. Given the available information, I'd imagine your collections are both likely picking up local lineages that share one or multiple mutations with the "identified" lineages. To investigate, you'd want to look at the frequency of XBB.1.5 specific mutations (e.g. S:F486P) and those corresponding to the additional lineages that were picked up.

Regarding some of the discrepancies- it's possible that they may have been due to clinical sequencing lags. I'd be curious to hear how things have gone since May. 

Josh

**Comment by joshuailevy** [comment]
Closing since this has been idle for a while now.
