### ISSUE TITLE
Dash request: minimising legend?

### ISSUE THREAD

**Issue by AliceMichie93** [andersen-lab/Freyja#157]
Hi there!

I have a pretty simple query. I'm loving the dash functionality, however, I find that the figure legend obscures some of the generated plots.
Is there a way to add a function to the .html to temporarily 'hide' the legend? Or is there already such a function that I've missed?

Thanks so much for your help,
Alice

**Comment by joshuailevy** [comment]
Hi @AliceMichie93! 

At the moment we don't have that functionality- but I agree, it does look as though the legend can sometimes creep into the upper right-most part of the dash plots. Would be an easy fix to just make sure that it's fully outside the plot. Can also look into "hiding" it, but for now we'll just move it so that it doesn't obscure anything. 

Josh

**Comment by AliceMichie93** [comment]
Thanks so much Josh
If you could just scoot the legend to the outside of the plot, that would be fantastic :)
Appreciate your help!
Alice
