### ISSUE TITLE
samtools not working with freyja install

### ISSUE THREAD

**Issue by dfeistel3** [andersen-lab/Freyja#18]
i keep getting an error when i run freyja:
`samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`

i get the same error when i run samtools alone in the freyja environment.

**Comment by joshuailevy** [comment]
Hi @dfeistel3! This issue was also encountered here: https://github.com/StaPH-B/docker-builds/pull/268 . Seems to be a conda version issue. 

Looks like some possible solutions were proposed here: https://github.com/merenlab/anvio/issues/1479

I'll look into making the appropriate changes later today.

**Comment by dfeistel3** [comment]
yep that works. `freyja demix` works now :)

**Comment by joshuailevy** [comment]
Great. I'll close this issue then, will do some additional testing to figure out what's going on as I prep the next release.
