### ISSUE TITLE
Wrong lineages?

### ISSUE THREAD

**Issue by LauraVP1994** [andersen-lab/Freyja#197]
Dear,

We are looking into how freyja performs depending on the coverage and allelic frequency of a lineage. For this purpose we used samples from SRA for which the Pangolin lineage is known. However, the results are not great. I used for example "pure" samples at different coverages and I got each time different results.

I added the results for the most problematic samples in the excel file. Probably the problem is that the lineages are close to eachother. However, in some cases I get 50% of one lineage and 50% of the parent lineage. 

For freyja, I used these parameters: --eps 0.025  --depthcutoff 500

[qual_samples.xlsx](https://github.com/andersen-lab/Freyja/files/13963322/qual_samples.xlsx)

I also tried without any parameters and then the results are a bit better except between BN.1/BN.1.1, BR.2/BR.2.1, XBB.1.5/XBB.1.25, XBB.1.5/XBB.2.11.1
[qual_samples_lofreq_nothreshold.xlsx](https://github.com/andersen-lab/Freyja/files/13963506/qual_samples_lofreq_nothreshold.xlsx)

Do you have any advice on how freyja can become more accurate. I would indeed expect that the tool is not perfect, but the dominant strain result should be the same?

**Comment by joshuailevy** [comment]
Hi @LauraVP1994, 

This sort of behavior is expected as you get to low sequencing coverages. Since there are thousands of lineages, many of which share the vast majority of their mutations, Freyja is often left with no information to differentiate between lineages. As such, it may "tie" between equally probable lineages provided the available data, hence the 50/50 outputs you're seeing. This isn't an accuracy issue per se, but rather a fundamental issue of unidentifiability in least squares/least absolution deviations problems, here caused by poor genome coverage. 

Since you're using the `--depthcutoff` option, it's worth being careful about what is actually contained in the collapsed groups that get generated as you increase the value of the parameter. If you make it high enough, you'll basically lump all of the known diversity of SARS-CoV-2 into a single group. 

Josh
