### ISSUE TITLE
[BUG]: barcode version is stuck on 04_30_2024-01-10

### ISSUE THREAD

**Issue by erinyoung** [andersen-lab/Freyja#236]
Hi!

I've been trying to stay current on the latest freyja barcodes. Even though I update the database, though, the current database is stuck on April 30.

The version that it's been stuck on for the last few days has been `04_30_2024-01-10`. I use `freyja demix --version` to get the version.

Are there no longer daily updates?

**Comment by joshuailevy** [comment]
Hey! 

Good question- there should still be data updates, but it seems like git diff check used in the automated workflow hasn't detected any changes in the barcodes since then. 

As far as I can tell, we haven't had any new lineages designated as of late, https://github.com/cov-lineages/pango-designation/commits/master/lineage_notes.txt. So it seems that it may just be that there's no updates to include. 

I can take a look later today to see if something is getting missed, but my hunch is that there's just no new lineages/designations to report. 

Josh

**Comment by joshuailevy** [comment]
This updated on the 11th, so I'll close it for now! Looks to have been a subtle update to the tree that changed a barcode slightly, a new lineage hasn't been proposed for quite a while now: https://github.com/cov-lineages/pango-designation/blob/master/lineage_notes.txt

**Comment by erinyoung** [comment]
Thank you for looking into this!
