### ISSUE TITLE
cvxpy.error.SolverError in freyja demix

### ISSUE THREAD

**Issue by evantroendle** [andersen-lab/Freyja#55]
Hello again,

Please see the output below that is halting the complete processing of some samples at the demix stage.
[NIRE-00387e_S25.bam.txt](https://github.com/andersen-lab/Freyja/files/8716733/NIRE-00387e_S25.bam.txt)
[NIRE-00387e_S25_freyja_variants.tsv.txt](https://github.com/andersen-lab/Freyja/files/8716750/NIRE-00387e_S25_freyja_variants.tsv.txt)
[NIRE-00387e_S25_freyja_depth.tsv.txt](https://github.com/andersen-lab/Freyja/files/8716760/NIRE-00387e_S25_freyja_depth.tsv.txt)

Thank you very much!
Evan

Commands and output traceback:
freyja variants NIRE-00387e_S25.bam --variants /media/evan/DATA2/freyja/NIRE-00387e_S25_freyja_variants.tsv --depths /media/evan/DATA2/freyja/NIRE-00387e_S25_freyja_depth.tsv --ref /home/evan/anaconda3/ipynb/SARS-COV-2/MN908947.3.fa
[mpileup] 1 samples in 1 input files
freyja demix /media/evan/DATA2/freyja/NIRE-00387e_S25_freyja_variants.tsv /media/evan/DATA2/freyja/NIRE-00387e_S25_freyja_depth.tsv --output /media/evan/DATA2/freyja/NIRE-00387e_S25_freyja_demix.tsv
building mix/depth matrices
demixing
Traceback (most recent call last):
  File "/home/evan/anaconda3/envs/freyja-env/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/freyja/_cli.py", line 49, in demix
    sample_strains, abundances, error = solve_demixing_problem(df_barcodes,
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/freyja/sample_deconv.py", line 139, in solve_demixing_problem
    prob.solve(verbose=False)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/cvxpy/problems/problem.py", line 481, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/cvxpy/problems/problem.py", line 1016, in _solve
    self.unpack_results(solution, solving_chain, inverse_data)
  File "/home/evan/anaconda3/envs/freyja-env/lib/python3.9/site-packages/cvxpy/problems/problem.py", line 1341, in unpack_results
    raise error.SolverError(
cvxpy.error.SolverError: Solver 'ECOS' failed. Try another solver, or solve with verbose=True for more information.

I will also list the conda environment packages below
#### Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39h7f8727e_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
attrs                     21.4.0             pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
beautifulsoup4            4.11.1           py39h06a4308_0  
bedtools                  2.30.0               h468198e_3    bioconda
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd3eb1b0_0  
boost-cpp                 1.74.0               h75c5d50_8    conda-forge
bottleneck                1.3.4            py39hce1f21e_0  
bowtie2                   2.4.5            py39hd2f7db1_2    bioconda
brotli                    1.0.9                he6710b0_2  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8        py39hf3d152e_2    conda-forge
cffi                      1.15.0           py39hd667e15_1  
click                     8.1.3            py39hf3d152e_0    conda-forge
cvxpy                     1.2.0            py39hf3d152e_0    conda-forge
cvxpy-base                1.2.0            py39h1832856_0    conda-forge
cycler                    0.11.0             pyhd3eb1b0_0  
dbus                      1.13.18              hb2f20db_0  
debugpy                   1.5.1            py39h295c915_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
ecos                      2.0.10           py39hce5d2b2_0    conda-forge
entrypoints               0.4              py39h06a4308_0  
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.4.4                h295c915_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.11.0               h70c0345_0  
freyja                    1.3.5              pyhdfd78af_0    bioconda
giflib                    5.2.1                h7b6447c_0  
glib                      2.69.1               h4ff587b_1  
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
hisat2                    2.1.0                h5005445_0    biobuilds
htslib                    1.14                 h9753748_2    bioconda
icu                       70.1                 h27087fc_0    conda-forge
intel-openmp              2021.4.0          h06a4308_3561  
ipykernel                 6.9.1            py39h06a4308_0  
ipython                   8.3.0            py39h06a4308_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
isa-l                     2.30.0               ha770c72_4    conda-forge
ivar                      1.3.1                hecb563c_3    bioconda
jbig                      2.1                  hdba287a_0  
jedi                      0.18.1           py39h06a4308_1  
jinja2                    3.0.3              pyhd3eb1b0_0  
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h7f8727e_0  
jsonschema                4.4.0            py39h06a4308_0  
jupyter_client            7.2.2            py39h06a4308_0  
jupyter_core              4.10.0           py39h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.3.2            py39h295c915_0  
krb5                      1.19.3               h3790be6_0    conda-forge
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
lerc                      3.0                  h295c915_0  
libblas                   3.9.0            12_linux64_mkl    conda-forge
libcbor                   0.9.0                h9c3ff4c_0    conda-forge
libcurl                   7.83.0               h7bff187_0    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  he6710b0_2  
libfido2                  1.11.0               h727a467_0    conda-forge
libgcc-ng                 11.2.0              h1d223b6_14    conda-forge
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   11.2.0              h1d223b6_14    conda-forge
liblapack                 3.9.0            12_linux64_mkl    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.18.1               h780b84a_0    conda-forge
libsodium                 1.0.18               h7b6447c_0  
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_14    conda-forge
libtiff                   4.3.0                h542a066_3    conda-forge
libudev1                  249                  h7f98852_1    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.2.2                h55f646e_0  
libwebp-base              1.2.2                h7f8727e_0  
libxcb                    1.14                 h7b6447c_0  
libzlib                   1.2.11            h166bdaf_1014    conda-forge
lz4-c                     1.9.3                h295c915_1  
mafft                     7.505                hec16e2b_0    bioconda
markupsafe                2.0.1            py39h27cfd23_0  
matplotlib                3.3.2                         0    conda-forge
matplotlib-base           3.3.2            py39h98787fa_1    conda-forge
matplotlib-inline         0.1.2              pyhd3eb1b0_2  
mistune                   0.8.4           py39h27cfd23_1000  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.1            py39hd3c417c_0  
mkl_random                1.2.2            py39h51133e4_0  
mosdepth                  0.3.3                hdfd78af_1    bioconda
mpi                       1.0                     openmpi    conda-forge
munkres                   1.1.4                      py_0  
mysql-connector-c         6.1.11            h6eb9d5d_1007    conda-forge
nb_conda_kernels          2.3.1            py39h06a4308_0  
nbclient                  0.5.13           py39h06a4308_0  
nbconvert                 6.4.4            py39h06a4308_0  
nbformat                  5.3.0            py39h06a4308_0  
ncurses                   6.3                  h7f8727e_2  
nest-asyncio              1.5.5            py39h06a4308_0  
nextclade                 1.11.0               h9ee0642_0    bioconda
notebook                  6.4.8            py39h06a4308_0  
numexpr                   2.8.1            py39h6abb31d_0  
numpy                     1.21.5           py39he7a7128_2  
numpy-base                1.21.5           py39hf524024_2  
openmpi                   4.1.3              hbea3300_101    conda-forge
openssh                   9.0p1                hf695f80_0    conda-forge
openssl                   1.1.1o               h166bdaf_0    conda-forge
osqp                      0.6.2.post0      py39hde0f152_3    conda-forge
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.4.2            py39h295c915_0  
pandocfilters             1.5.0              pyhd3eb1b0_0  
parso                     0.8.3              pyhd3eb1b0_0  
pcre                      8.45                 h295c915_0  
perl                      5.26.2               h14c3975_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.0.1            py39h22f2fdc_0  
pip                       21.2.4           py39h06a4308_0  
prometheus_client         0.13.1             pyhd3eb1b0_0  
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.11.2             pyhd3eb1b0_0  
pyparsing                 3.0.4              pyhd3eb1b0_0  
pyrsistent                0.18.0           py39heee7806_0  
python                    3.9.12               h12debd9_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.15.1             pyhd3eb1b0_0  
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd3eb1b0_0  
pyzmq                     22.3.0           py39h295c915_2  
qdldl-python              0.1.5            py39hde0f152_2    conda-forge
readline                  8.1.2                h7f8727e_1  
samtools                  1.15                 h3843a85_0    bioconda
scipy                     1.7.3            py39hc147768_0  
scs                       3.2.0            py39h0ec8588_0    conda-forge
seaborn                   0.11.2             pyhd3eb1b0_0  
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                61.2.0           py39h06a4308_0  
sip                       4.19.13          py39h295c915_0  
six                       1.16.0             pyhd3eb1b0_1  
soupsieve                 2.3.1              pyhd3eb1b0_0  
sqlite                    3.38.2               hc218d9a_0  
stack_data                0.2.0              pyhd3eb1b0_0  
tbb                       2020.3               hfd86e86_0  
terminado                 0.13.1           py39h06a4308_0  
testpath                  0.5.0              pyhd3eb1b0_0  
tk                        8.6.11               h1ccaba5_0  
tornado                   6.1              py39h27cfd23_0  
tqdm                      4.64.0           py39h06a4308_0  
traitlets                 5.1.1              pyhd3eb1b0_0  
typing-extensions         4.1.1                hd3eb1b0_0  
typing_extensions         4.1.1              pyh06a4308_0  
tzdata                    2022a                hda174b7_0  
ucsc-fatovcf              426                  h954228d_0    bioconda
usher                     0.5.4                hf1ae886_0    bioconda
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1            py39h06a4308_1  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.5                h7f8727e_1  
zeromq                    4.3.4                h2531618_0  
zlib                      1.2.11            h166bdaf_1014    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge

**Comment by joshuailevy** [comment]
Hey! 

That's an interesting error. I've seen solver convergence warnings every once in a while, but I don't think I've ever seen a error message like that when demixing a sample! 

I ran your sample in both Freyja 1.3.6 and as well as an older version of the package (only difference for this stuff should be that a few of the dependencies have been updated a bit). I don't see any error message for the newer version, but for the old one I get a warning (rather than an error) of a possible solver convergence issue similar to what you found. However for both versions it returns the same exact thing (sample is AY.4) as shown here
[test387.output.txt](https://github.com/andersen-lab/Freyja/files/8718081/test387.output.txt).  Is it possible that you haven't done a ```freyja update``` command in a while? I wouldn't expect it to be a python version issue, and we're using the same cvxpy and ecos versions, so I'm not quite sure what's going on. What OS are you running? 

Here's a list of the packages in my conda env: 

appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
boost-cpp                 1.74.0               hdbf7018_7    conda-forge
brotli                    1.0.9                h0d85af4_6    conda-forge
brotli-bin                1.0.9                h0d85af4_6    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2021.10.8            h033912b_0    conda-forge
certifi                   2021.10.8       py310h2ec42d9_2    conda-forge
click                     8.1.2           py310h2ec42d9_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cvxpy                     1.2.0           py310h2ec42d9_0    conda-forge
cvxpy-base                1.2.0           py310h514ec25_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
ecos                      2.0.10          py310h81f86ea_0    conda-forge
executing                 0.8.3              pyhd8ed1ab_0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
freyja                    1.3.6              pyhdfd78af_0    bioconda
giflib                    5.2.1                hbcb3906_2    conda-forge
htslib                    1.14                 hc38c3fb_0    bioconda
icu                       69.1                 he49afe7_0    conda-forge
ipython                   8.2.0           py310h2ec42d9_0    conda-forge
iqtree                    2.2.0_beta           h135ad0d_1    bioconda
isa-l                     2.30.0               h0d85af4_4    conda-forge
ivar                      1.3.1                he901cdd_3    bioconda
jbig                      2.1               h0d85af4_2003    conda-forge
jedi                      0.18.1          py310h2ec42d9_1    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0d85af4_0    conda-forge
kiwisolver                1.4.2           py310h6be76da_1    conda-forge
krb5                      1.19.3               hb49756b_0    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      2.2.1                h046ec9c_0    conda-forge
libblas                   3.9.0           13_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                h0d85af4_6    conda-forge
libbrotlidec              1.0.9                h0d85af4_6    conda-forge
libbrotlienc              1.0.9                h0d85af4_6    conda-forge
libcblas                  3.9.0           13_osx64_openblas    conda-forge
libcbor                   0.9.0                he49afe7_0    conda-forge
libcurl                   7.82.0               h9f20792_0    conda-forge
libcxx                    13.0.1               hc203e6f_0    conda-forge
libdeflate                1.7                  h35c211d_5    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libfido2                  1.10.0               h64a5342_0    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
liblapack                 3.9.0           13_osx64_openblas    conda-forge
libnghttp2                1.47.0               h942079c_0    conda-forge
libopenblas               0.3.18          openmp_h3351f45_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libprotobuf               3.18.1               hcf210ce_0    conda-forge
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libtiff                   4.3.0                h1167814_1    conda-forge
libuuid                   2.32.1            h35c211d_1000    conda-forge
libwebp                   1.2.2                h28dabe5_0    conda-forge
libwebp-base              1.2.2                h0d85af4_1    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libzlib                   1.2.11            h9173be1_1013    conda-forge
llvm-openmp               13.0.1               hcb1a161_1    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
mafft                     7.490                hb4d813b_0    bioconda
matplotlib-base           3.4.3           py310hfc59cd6_2    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mpi                       1.0                     openmpi    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-connector-c         6.1.11            h0f02589_1007    conda-forge
ncurses                   6.3                  he49afe7_0    conda-forge
numpy                     1.22.3          py310hb608527_1    conda-forge
openjpeg                  2.4.0                h6e7aa92_1    conda-forge
openmpi                   4.1.2                hd3cd54c_0    conda-forge
openssh                   8.9p1                hd27dfd1_0    conda-forge
openssl                   1.1.1o               hfe4f2af_0    conda-forge
osqp                      0.6.2.post0     py310hdd25497_3    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.2           py310h514ec25_0    conda-forge
parallel                  20220222             h694c41f_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
perl                      5.32.1          2_h0d85af4_perl5    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.1.0           py310h382dc3b_0    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.29             pyha770c72_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
python                    3.10.4          h8b4d769_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
qdldl-python              0.1.5           py310hdd25497_2    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
samtools                  1.15                 hb35f05f_0    bioconda
scipy                     1.8.0           py310h47774c9_1    conda-forge
scs                       3.2.0           py310hf353fc2_0    conda-forge
setuptools                62.0.0          py310h2ec42d9_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.37.1               hb516253_0    conda-forge
stack_data                0.2.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
tornado                   6.1             py310h1961e1f_3    conda-forge
tqdm                      4.63.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typing-extensions         4.1.1                hd8ed1ab_0    conda-forge
typing_extensions         4.1.1              pyha770c72_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
ucsc-fatovcf              426                  ha55e18d_0    bioconda
usher                     0.5.3                h32fa512_0    bioconda
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
zlib                      1.2.11            h9173be1_1013    conda-forge
zstd                      1.5.2                h582d3a0_0    conda-forge

**Comment by evantroendle** [comment]
Hi Josh,

I probably last ran freyja update a couple of weeks back. For now, I have decided then to rerun the analysis over all samples with an updated freyja (v 1.3.6) and calling freyja update after the installation. I will get back to you with the results. As for the OS it's Ubuntu 20.04.4 LTS.

**Comment by joshuailevy** [comment]
Got it. I don't think updating should have much of an impact (AY.4 has been around for quite a while), but worth giving it a shot.  Would be surprised if it's an OS issue, I've tested the code pretty extensively on Ubuntu (both 18.04 and 20.04). Let me know how it goes though!

Josh

**Comment by joshuailevy** [comment]
Closing this because it's been a while, but happy to open it again if this issue keeps popping up.

**Comment by charlesfoster** [comment]
Hi,
Reopening this issue because we've begun getting the same error message:

```
Traceback (most recent call last):
  File "/opt/conda/envs/freyja-env/bin/freyja", line 10, in <module>
    sys.exit(cli())
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/freyja/_cli.py", line 61, in demix
    sample_strains, abundances, error = solve_demixing_problem(df_barcodes,
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/freyja/sample_deconv.py", line 139, in solve_demixing_problem
    prob.solve(verbose=False)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 481, in solve
    return solve_func(self, *args, **kwargs)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 1020, in _solve
    self.unpack_results(solution, solving_chain, inverse_data)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/cvxpy/problems/problem.py", line 1345, in unpack_results
    raise error.SolverError(
cvxpy.error.SolverError: Solver 'ECOS' failed. Try another solver, or solve with verbose=True for more information.
```

We're running freyja using singularity with the StaPH-B freyja Docker image (v 1.3.11; https://hub.docker.com/layers/staphb/freyja/1.3.11/images/sha256-6766e10657bd473fa908ecaec20a3e9558a330694e59430060468ae9d97f247b?context=explore). Command:

```
gunzip -c sample.lofreq.vcf.gz > sample.vcf
freyja demix sample.vcf sample.depths --output sample.demix --barcodes usher_barcodes.csv 
```
I've run the same samples using freyja v1.3.12 and get the same error. Input files attached (had to rename with .txt extension so they'd attach).

Any help would be appreciated.

[sample.depths.txt](https://github.com/andersen-lab/Freyja/files/10514236/sample.depths.txt)
[sample.vcf.txt](https://github.com/andersen-lab/Freyja/files/10514247/sample.vcf.txt)
